"use client"

import { useState, useEffect, useMemo } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { useAlertModal } from "@/components/AlertModal"

type Category = {
  id: string
  name: string
  description: string | null
  minAge: number | null
  maxAge: number | null
  cultureTags: string[]
  isAutoGenerated: boolean
  sourceTag: string | null
  _count?: {
    stories: number
  }
}

export default function AdminCategoriesPage() {
  const router = useRouter()
  const { AlertModal, showAlert, showConfirm } = useAlertModal()
  const [categories, setCategories] = useState<Category[]>([])
  const [loading, setLoading] = useState(false)
  const [showForm, setShowForm] = useState(false)
  const [searchQuery, setSearchQuery] = useState("")
  const [sortBy, setSortBy] = useState<"name" | "stories" | "age">("name")
  const [typeFilter, setTypeFilter] = useState<"all" | "auto" | "manual">("all")
  const [ageFilter, setAgeFilter] = useState<string>("all")
  const [formData, setFormData] = useState({
    name: "",
    description: "",
    minAge: "",
    maxAge: "",
    cultureTags: "",
  })

  useEffect(() => {
    fetchCategories()
  }, [])

  const fetchCategories = async () => {
    try {
      const res = await fetch("/api/admin/categories")
      if (res.ok) {
        const data = await res.json()
        setCategories(data)
      }
    } catch (error) {
      console.error("Error fetching categories:", error)
    }
  }

  const handleRegenerateCategories = async () => {
    const confirmed = await showConfirm(
      "This will regenerate all auto-generated categories from existing stories. Continue?",
      "Regenerate Categories"
    )
    if (!confirmed) {
      return
    }
    
    setLoading(true)
    try {
      const res = await fetch("/api/admin/categories/regenerate", {
        method: "POST",
      })
      if (res.ok) {
        await showAlert("Categories regenerated successfully!")
        fetchCategories()
      } else {
        await showAlert("Failed to regenerate categories")
      }
    } catch (error) {
      console.error("Error regenerating categories:", error)
      await showAlert("Error regenerating categories")
    } finally {
      setLoading(false)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)

    try {
      const res = await fetch("/api/admin/categories", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ...formData,
          minAge: formData.minAge ? parseInt(formData.minAge) : null,
          maxAge: formData.maxAge ? parseInt(formData.maxAge) : null,
          cultureTags: formData.cultureTags
            .split(",")
            .map((t) => t.trim())
            .filter(Boolean),
        }),
      })

      if (res.ok) {
        setFormData({ name: "", description: "", minAge: "", maxAge: "", cultureTags: "" })
        setShowForm(false)
        fetchCategories()
      }
    } catch (error) {
      console.error("Error creating category:", error)
    } finally {
      setLoading(false)
    }
  }

  const filteredAndSortedCategories = useMemo(() => {
    let filtered = categories.filter((cat) => {
      // Search filter
      const query = searchQuery.toLowerCase().trim()
      if (query) {
        const matchesSearch =
          cat.name.toLowerCase().includes(query) ||
          (cat.description && cat.description.toLowerCase().includes(query)) ||
          cat.cultureTags.some((tag) => tag.toLowerCase().includes(query)) ||
          (cat.sourceTag && cat.sourceTag.toLowerCase().includes(query))
        if (!matchesSearch) return false
      }

      // Type filter
      if (typeFilter === "auto" && !cat.isAutoGenerated) return false
      if (typeFilter === "manual" && cat.isAutoGenerated) return false

      // Age filter
      if (ageFilter !== "all") {
        const [min, max] = ageFilter.split("-").map(Number)
        if (cat.minAge === null || cat.maxAge === null) return false
        if (cat.minAge > max || cat.maxAge < min) return false
      }

      return true
    })

    // Sort categories
    filtered = [...filtered].sort((a, b) => {
      switch (sortBy) {
        case "name":
          return a.name.localeCompare(b.name)
        case "stories":
          return (b._count?.stories || 0) - (a._count?.stories || 0)
        case "age":
          const aAge = a.minAge || 0
          const bAge = b.minAge || 0
          return aAge - bAge
        default:
          return 0
      }
    })

    return filtered
  }, [categories, searchQuery, sortBy, typeFilter, ageFilter])

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold text-foreground">Categories</h1>
          <p className="text-foreground/70 mt-1">
            Categories are automatically generated from story tags. You can also create manual categories.
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleRegenerateCategories}
            disabled={loading}
            className="bg-card-bg text-foreground px-4 py-2 rounded-lg hover:bg-border-color border border-border-color disabled:opacity-50 transition-colors"
          >
            Regenerate Auto Categories
          </button>
          <button
            onClick={() => setShowForm(!showForm)}
            className="bg-accent-purple text-white px-4 py-2 rounded-lg hover:bg-accent-purple-dark transition-colors"
          >
            {showForm ? "Cancel" : "+ New Manual Category"}
          </button>
        </div>
      </div>

      {/* Search and Filter Controls */}
      <div className="bg-card-bg rounded-lg shadow-lg p-4 border border-border-color space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Search */}
          <div className="lg:col-span-2">
            <input
              type="text"
              placeholder="Search by name, description, or tags..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-background border border-border-color rounded-lg px-4 py-2 text-foreground placeholder:text-foreground/50 focus:outline-none focus:ring-2 focus:ring-accent-purple"
            />
          </div>

          {/* Sort */}
          <div>
            <select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value as typeof sortBy)}
              className="w-full bg-background border border-border-color rounded-lg px-4 py-2 text-foreground focus:outline-none focus:ring-2 focus:ring-accent-purple"
            >
              <option value="name">Name A-Z</option>
              <option value="stories">Most Stories</option>
              <option value="age">Age Range</option>
            </select>
          </div>

          {/* Type Filter */}
          <div>
            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value as typeof typeFilter)}
              className="w-full bg-background border border-border-color rounded-lg px-4 py-2 text-foreground focus:outline-none focus:ring-2 focus:ring-accent-purple"
            >
              <option value="all">All Types</option>
              <option value="auto">Auto Generated</option>
              <option value="manual">Manual</option>
            </select>
          </div>

          {/* Age Filter */}
          <div>
            <select
              value={ageFilter}
              onChange={(e) => setAgeFilter(e.target.value)}
              className="w-full bg-background border border-border-color rounded-lg px-4 py-2 text-foreground focus:outline-none focus:ring-2 focus:ring-accent-purple"
            >
              <option value="all">All Ages</option>
              <option value="3-5">Ages 3-5</option>
              <option value="4-7">Ages 4-7</option>
              <option value="6-9">Ages 6-9</option>
              <option value="8-12">Ages 8-12</option>
            </select>
          </div>
        </div>

        {/* Clear Filters */}
        {(searchQuery || typeFilter !== "all" || ageFilter !== "all") && (
          <button
            onClick={() => {
              setSearchQuery("")
              setTypeFilter("all")
              setAgeFilter("all")
            }}
            className="text-sm text-accent-purple hover:text-accent-purple-dark transition-colors"
          >
            Clear all filters
          </button>
        )}
      </div>

      {/* Results Count */}
      <div className="text-sm text-foreground/70">
        Showing {filteredAndSortedCategories.length} of {categories.length} categories
      </div>

      {showForm && (
        <form
          onSubmit={handleSubmit}
          className="bg-card-bg rounded-lg shadow-lg p-6 space-y-4 border border-border-color"
        >
          <div>
            <label className="block text-sm font-medium text-foreground/90 mb-2">
              Name *
            </label>
            <input
              type="text"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              required
              className="w-full px-3 py-2 border border-border-color rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-accent-purple"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-foreground/90 mb-2">
              Description
            </label>
            <textarea
              value={formData.description}
              onChange={(e) =>
                setFormData({ ...formData, description: e.target.value })
              }
              rows={3}
              className="w-full px-3 py-2 border border-border-color rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-accent-purple"
            />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-foreground/90 mb-2">
                Min Age
              </label>
              <input
                type="number"
                value={formData.minAge}
                onChange={(e) =>
                  setFormData({ ...formData, minAge: e.target.value })
                }
                className="w-full px-3 py-2 border border-border-color rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-accent-purple"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-foreground/90 mb-2">
                Max Age
              </label>
              <input
                type="number"
                value={formData.maxAge}
                onChange={(e) =>
                  setFormData({ ...formData, maxAge: e.target.value })
                }
                className="w-full px-3 py-2 border border-border-color rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-accent-purple"
              />
            </div>
          </div>
          <div>
            <label className="block text-sm font-medium text-foreground/90 mb-2">
              Culture Tags (comma-separated)
            </label>
            <input
              type="text"
              value={formData.cultureTags}
              onChange={(e) =>
                setFormData({ ...formData, cultureTags: e.target.value })
              }
              className="w-full px-3 py-2 border border-border-color rounded-md bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-accent-purple"
            />
          </div>
          <button
            type="submit"
            disabled={loading}
            className="px-4 py-2 bg-accent-purple text-white rounded-lg hover:bg-accent-purple-dark disabled:opacity-50 transition-colors"
          >
            {loading ? "Creating..." : "Create Category"}
          </button>
        </form>
      )}

      <div className="bg-card-bg rounded-lg shadow-lg overflow-hidden border border-border-color">
        <table className="min-w-full divide-y divide-border-color">
          <thead className="bg-background/50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-foreground/70 uppercase tracking-wider">
                Name
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-foreground/70 uppercase tracking-wider">
                Description
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-foreground/70 uppercase tracking-wider">
                Age Range
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-foreground/70 uppercase tracking-wider">
                Stories
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium text-foreground/70 uppercase tracking-wider">
                Type
              </th>
            </tr>
          </thead>
          <tbody className="bg-card-bg divide-y divide-border-color">
            {filteredAndSortedCategories.length === 0 ? (
              <tr>
                <td colSpan={5} className="px-6 py-8 text-center text-foreground/70">
                  No categories found matching your filters.
                </td>
              </tr>
            ) : (
              filteredAndSortedCategories.map((cat) => (
                <tr key={cat.id} className="hover:bg-background/30 transition-colors">
                <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-foreground">
                  {cat.name}
                </td>
                <td className="px-6 py-4 text-sm text-foreground/70">
                  {cat.description || "-"}
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-foreground/70">
                  {cat.minAge && cat.maxAge ? `${cat.minAge}-${cat.maxAge}` : "-"}
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-foreground/70">
                  {cat._count?.stories || 0}
                </td>
                <td className="px-6 py-4 whitespace-nowrap">
                  {cat.isAutoGenerated ? (
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-accent-purple/20 text-accent-purple border border-accent-purple/30">
                      Auto
                    </span>
                  ) : (
                    <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-foreground/10 text-foreground/80 border border-border-color">
                      Manual
                    </span>
                  )}
                </td>
              </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
      <AlertModal />
    </div>
  )
}

